(cl:in-package plutodrone-srv)
(cl:export '(ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          ACCX-VAL
          ACCX
          ACCY-VAL
          ACCY
          ACCZ-VAL
          ACCZ
          GYROX-VAL
          GYROX
          GYROY-VAL
          GYROY
          GYROZ-VAL
          GYROZ
          MAGX-VAL
          MAGX
          MAGY-VAL
          MAGY
          MAGZ-VAL
          MAGZ
          ALT-VAL
          ALT
          BATTERY-VAL
          BATTERY
          RSSI-VAL
          RSSI
          A1-VAL
          A1
          A2-VAL
          A2
          A3-VAL
          A3
          RCROLL-VAL
          RCROLL
          RCPITCH-VAL
          RCPITCH
          RCYAW-VAL
          RCYAW
          RCTHROTTLE-VAL
          RCTHROTTLE
          RCAUX1-VAL
          RCAUX1
          RCAUX2-VAL
          RCAUX2
          RCAUX3-VAL
          RCAUX3
          RCAUX4-VAL
          RCAUX4
))