(cl:defpackage plutodrone-srv
  (:use )
  (:export
   "PLUTOPILOT"
   "<PLUTOPILOT-REQUEST>"
   "PLUTOPILOT-REQUEST"
   "<PLUTOPILOT-RESPONSE>"
   "PLUTOPILOT-RESPONSE"
   "ARUCO"
   "<ARUCO-REQUEST>"
   "ARUCO-REQUEST"
   "<ARUCO-RESPONSE>"
   "ARUCO-RESPONSE"
  ))

