// Generated by gencpp from file plutodrone/arucoResponse.msg
// DO NOT EDIT!


#ifndef PLUTODRONE_MESSAGE_ARUCORESPONSE_H
#define PLUTODRONE_MESSAGE_ARUCORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plutodrone
{
template <class ContainerAllocator>
struct arucoResponse_
{
  typedef arucoResponse_<ContainerAllocator> Type;

  arucoResponse_()
    : data()  {
    }
  arucoResponse_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::plutodrone::arucoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plutodrone::arucoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct arucoResponse_

typedef ::plutodrone::arucoResponse_<std::allocator<void> > arucoResponse;

typedef boost::shared_ptr< ::plutodrone::arucoResponse > arucoResponsePtr;
typedef boost::shared_ptr< ::plutodrone::arucoResponse const> arucoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plutodrone::arucoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plutodrone::arucoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plutodrone::arucoResponse_<ContainerAllocator1> & lhs, const ::plutodrone::arucoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plutodrone::arucoResponse_<ContainerAllocator1> & lhs, const ::plutodrone::arucoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plutodrone

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::plutodrone::arucoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plutodrone::arucoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plutodrone::arucoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plutodrone::arucoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plutodrone::arucoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plutodrone::arucoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plutodrone::arucoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8560fbebb34fa1b9472337b5c3d38fda";
  }

  static const char* value(const ::plutodrone::arucoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8560fbebb34fa1b9ULL;
  static const uint64_t static_value2 = 0x472337b5c3d38fdaULL;
};

template<class ContainerAllocator>
struct DataType< ::plutodrone::arucoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plutodrone/arucoResponse";
  }

  static const char* value(const ::plutodrone::arucoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plutodrone::arucoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[] data  # Response: The array of int16 values\n"
"\n"
;
  }

  static const char* value(const ::plutodrone::arucoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plutodrone::arucoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arucoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plutodrone::arucoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plutodrone::arucoResponse_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLUTODRONE_MESSAGE_ARUCORESPONSE_H
