// Generated by gencpp from file plutodrone/arucoRequest.msg
// DO NOT EDIT!


#ifndef PLUTODRONE_MESSAGE_ARUCOREQUEST_H
#define PLUTODRONE_MESSAGE_ARUCOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plutodrone
{
template <class ContainerAllocator>
struct arucoRequest_
{
  typedef arucoRequest_<ContainerAllocator> Type;

  arucoRequest_()
    : size(0)  {
    }
  arucoRequest_(const ContainerAllocator& _alloc)
    : size(0)  {
  (void)_alloc;
    }



   typedef int32_t _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::plutodrone::arucoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plutodrone::arucoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct arucoRequest_

typedef ::plutodrone::arucoRequest_<std::allocator<void> > arucoRequest;

typedef boost::shared_ptr< ::plutodrone::arucoRequest > arucoRequestPtr;
typedef boost::shared_ptr< ::plutodrone::arucoRequest const> arucoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plutodrone::arucoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plutodrone::arucoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plutodrone::arucoRequest_<ContainerAllocator1> & lhs, const ::plutodrone::arucoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.size == rhs.size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plutodrone::arucoRequest_<ContainerAllocator1> & lhs, const ::plutodrone::arucoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plutodrone

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::plutodrone::arucoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plutodrone::arucoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plutodrone::arucoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plutodrone::arucoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plutodrone::arucoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plutodrone::arucoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plutodrone::arucoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97da5de9999c5ce84f539773c8d0b2a3";
  }

  static const char* value(const ::plutodrone::arucoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97da5de9999c5ce8ULL;
  static const uint64_t static_value2 = 0x4f539773c8d0b2a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::plutodrone::arucoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plutodrone/arucoRequest";
  }

  static const char* value(const ::plutodrone::arucoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plutodrone::arucoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 size  # Request: The number of elements in the array\n"
;
  }

  static const char* value(const ::plutodrone::arucoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plutodrone::arucoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arucoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plutodrone::arucoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plutodrone::arucoRequest_<ContainerAllocator>& v)
  {
    s << indent << "size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLUTODRONE_MESSAGE_ARUCOREQUEST_H
