// Generated by gencpp from file plutodrone/aruco.msg
// DO NOT EDIT!


#ifndef PLUTODRONE_MESSAGE_ARUCO_H
#define PLUTODRONE_MESSAGE_ARUCO_H

#include <ros/service_traits.h>


#include <plutodrone/arucoRequest.h>
#include <plutodrone/arucoResponse.h>


namespace plutodrone
{

struct aruco
{

typedef arucoRequest Request;
typedef arucoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct aruco
} // namespace plutodrone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plutodrone::aruco > {
  static const char* value()
  {
    return "c31722818caef8e97292f53a960b806f";
  }

  static const char* value(const ::plutodrone::aruco&) { return value(); }
};

template<>
struct DataType< ::plutodrone::aruco > {
  static const char* value()
  {
    return "plutodrone/aruco";
  }

  static const char* value(const ::plutodrone::aruco&) { return value(); }
};


// service_traits::MD5Sum< ::plutodrone::arucoRequest> should match
// service_traits::MD5Sum< ::plutodrone::aruco >
template<>
struct MD5Sum< ::plutodrone::arucoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plutodrone::aruco >::value();
  }
  static const char* value(const ::plutodrone::arucoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plutodrone::arucoRequest> should match
// service_traits::DataType< ::plutodrone::aruco >
template<>
struct DataType< ::plutodrone::arucoRequest>
{
  static const char* value()
  {
    return DataType< ::plutodrone::aruco >::value();
  }
  static const char* value(const ::plutodrone::arucoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plutodrone::arucoResponse> should match
// service_traits::MD5Sum< ::plutodrone::aruco >
template<>
struct MD5Sum< ::plutodrone::arucoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plutodrone::aruco >::value();
  }
  static const char* value(const ::plutodrone::arucoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plutodrone::arucoResponse> should match
// service_traits::DataType< ::plutodrone::aruco >
template<>
struct DataType< ::plutodrone::arucoResponse>
{
  static const char* value()
  {
    return DataType< ::plutodrone::aruco >::value();
  }
  static const char* value(const ::plutodrone::arucoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUTODRONE_MESSAGE_ARUCO_H
