// Generated by gencpp from file plutodrone/SetPos.msg
// DO NOT EDIT!


#ifndef PLUTODRONE_MESSAGE_SETPOS_H
#define PLUTODRONE_MESSAGE_SETPOS_H

#include <ros/service_traits.h>


#include <plutodrone/SetPosRequest.h>
#include <plutodrone/SetPosResponse.h>


namespace plutodrone
{

struct SetPos
{

typedef SetPosRequest Request;
typedef SetPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPos
} // namespace plutodrone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plutodrone::SetPos > {
  static const char* value()
  {
    return "0887ae55fe5cc3ab69632861e1865920";
  }

  static const char* value(const ::plutodrone::SetPos&) { return value(); }
};

template<>
struct DataType< ::plutodrone::SetPos > {
  static const char* value()
  {
    return "plutodrone/SetPos";
  }

  static const char* value(const ::plutodrone::SetPos&) { return value(); }
};


// service_traits::MD5Sum< ::plutodrone::SetPosRequest> should match
// service_traits::MD5Sum< ::plutodrone::SetPos >
template<>
struct MD5Sum< ::plutodrone::SetPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plutodrone::SetPos >::value();
  }
  static const char* value(const ::plutodrone::SetPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plutodrone::SetPosRequest> should match
// service_traits::DataType< ::plutodrone::SetPos >
template<>
struct DataType< ::plutodrone::SetPosRequest>
{
  static const char* value()
  {
    return DataType< ::plutodrone::SetPos >::value();
  }
  static const char* value(const ::plutodrone::SetPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plutodrone::SetPosResponse> should match
// service_traits::MD5Sum< ::plutodrone::SetPos >
template<>
struct MD5Sum< ::plutodrone::SetPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plutodrone::SetPos >::value();
  }
  static const char* value(const ::plutodrone::SetPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plutodrone::SetPosResponse> should match
// service_traits::DataType< ::plutodrone::SetPos >
template<>
struct DataType< ::plutodrone::SetPosResponse>
{
  static const char* value()
  {
    return DataType< ::plutodrone::SetPos >::value();
  }
  static const char* value(const ::plutodrone::SetPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUTODRONE_MESSAGE_SETPOS_H
