// Generated by gencpp from file plutodrone/SetPosResponse.msg
// DO NOT EDIT!


#ifndef PLUTODRONE_MESSAGE_SETPOSRESPONSE_H
#define PLUTODRONE_MESSAGE_SETPOSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plutodrone
{
template <class ContainerAllocator>
struct SetPosResponse_
{
  typedef SetPosResponse_<ContainerAllocator> Type;

  SetPosResponse_()
    : set_x(0.0)
    , set_y(0.0)
    , set_z(0.0)  {
    }
  SetPosResponse_(const ContainerAllocator& _alloc)
    : set_x(0.0)
    , set_y(0.0)
    , set_z(0.0)  {
  (void)_alloc;
    }



   typedef double _set_x_type;
  _set_x_type set_x;

   typedef double _set_y_type;
  _set_y_type set_y;

   typedef double _set_z_type;
  _set_z_type set_z;





  typedef boost::shared_ptr< ::plutodrone::SetPosResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plutodrone::SetPosResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetPosResponse_

typedef ::plutodrone::SetPosResponse_<std::allocator<void> > SetPosResponse;

typedef boost::shared_ptr< ::plutodrone::SetPosResponse > SetPosResponsePtr;
typedef boost::shared_ptr< ::plutodrone::SetPosResponse const> SetPosResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plutodrone::SetPosResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plutodrone::SetPosResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plutodrone::SetPosResponse_<ContainerAllocator1> & lhs, const ::plutodrone::SetPosResponse_<ContainerAllocator2> & rhs)
{
  return lhs.set_x == rhs.set_x &&
    lhs.set_y == rhs.set_y &&
    lhs.set_z == rhs.set_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plutodrone::SetPosResponse_<ContainerAllocator1> & lhs, const ::plutodrone::SetPosResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plutodrone

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::plutodrone::SetPosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plutodrone::SetPosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plutodrone::SetPosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plutodrone::SetPosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plutodrone::SetPosResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plutodrone::SetPosResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plutodrone::SetPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5da85cbf47c5f9f317e3ca08de41a4e";
  }

  static const char* value(const ::plutodrone::SetPosResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5da85cbf47c5f9fULL;
  static const uint64_t static_value2 = 0x317e3ca08de41a4eULL;
};

template<class ContainerAllocator>
struct DataType< ::plutodrone::SetPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plutodrone/SetPosResponse";
  }

  static const char* value(const ::plutodrone::SetPosResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plutodrone::SetPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 set_x\n"
"float64 set_y\n"
"float64 set_z\n"
"\n"
;
  }

  static const char* value(const ::plutodrone::SetPosResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plutodrone::SetPosResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.set_x);
      stream.next(m.set_y);
      stream.next(m.set_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPosResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plutodrone::SetPosResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plutodrone::SetPosResponse_<ContainerAllocator>& v)
  {
    s << indent << "set_x: ";
    Printer<double>::stream(s, indent + "  ", v.set_x);
    s << indent << "set_y: ";
    Printer<double>::stream(s, indent + "  ", v.set_y);
    s << indent << "set_z: ";
    Printer<double>::stream(s, indent + "  ", v.set_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLUTODRONE_MESSAGE_SETPOSRESPONSE_H
