(cl:in-package plutodrone-msg)
(cl:export '(ACCX-VAL
          ACCX
          ACCY-VAL
          ACCY
          ACCZ-VAL
          ACCZ
          GYROX-VAL
          GYROX
          GYROY-VAL
          GYROY
          GYROZ-VAL
          GYROZ
          MAGX-VAL
          MAGX
          MAGY-VAL
          MAGY
          MAGZ-VAL
          MAGZ
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          ALT-VAL
          ALT
          BATTERY-VAL
          BATTERY
          RSSI-VAL
          RSSI
          A1-VAL
          A1
          A2-VAL
          A2
          A3-VAL
          A3
))